const questionList = {
  english: [
    {
      QuestionNumber: 1,
      question: "1. ____ is the most loved sports in india.",
      type: "Fill In The Blanks",
      options: ["cricket", "football", "hockey", "kabaddi"],
      Answer: "cricket",
      Answered: true,
      correct: false,
      selectedAns: [],
    },
    {
      QuestionNumber: 2,
      question: "2.which cricketer is from south africa",
      type: "MCQ",
      options: [
        "virat kohli",
        "kane williamSon",
        "AB devilliers",
        "jos buttler",
      ],
      Answer: "AB devilliers",
      Answered: false,
      correct: false,
      selectedAns: [],
    },
    {
      QuestionNumber: 3,
      question: "3.english is the national language of india ",
      type: "True Or False",
      options: ["true", "false"],
      Answer: "false",
      Answered: false,
      correct: false,
      selectedAns: [],
    },
    {
      QuestionNumber: 4,
      question: `4.asdfg  ertyrew  <br>
      jhgfrerghgfr\n
      hytrertghgtr`,
      type: "Match The Following",
      options: [
        "a->b,b->c,c->d,d->a",
        "a->c,b->a,c->d,d->b",
        "a->d,b->c,c->b,d->a",
        "a->a,b->c,c->b,d->d",
      ],
      Answer: "a->b,b->c,c->d,d->a",
      Answered: false,
      correct: false,
      selectedAns: [],
    },
    {
      QuestionNumber: 5,
      question: "5.Select True options",
      type: "Multi Select",
      options: ["1>2", "5>=3", "1=0", "9<11"],
      Answer: [ "5>=3","9<11"],
      Answered: false,
      correct: false,
      selectedAns: [],
    },
  ],
  hindi: [
    {
      QuestionNumber: "१",
      question: "1.२+२=___",
      type: "Fill In The Blanks",
      options: ["१", "२", "३", "४"],
      Answer: "४",
      Answered: false,
      correct: false,
      selectedAns: [],
    },
    {
      QuestionNumber: "२",
      question: "2.३*८ = ?",
      type: "MCQ",
      options: ["११", "२४", "0", "७६"],
      Answer: "२४",
      Answered: false,
      correct: false,
      selectedAns: [],
    },
    {
      QuestionNumber: "३",
      question: "3.१>२",
      type: "True Or False",
      options: ["सही", "गलत"],
      Answer: "गलत",
      Answered: false,
      correct: false,
      selectedAns: [],
    },
    {
      QuestionNumber: "४",
      question: "4.who invented c language",
      type: "Match The Following",
      options: [
        "a->b,b->c,c->d,d->a",
        "a->c,b->a,c->d,d->b",
        "a->d,b->c,c->b,d->a",
        "a->a,b->c,c->b,d->d",
      ],
      Answer: "a->b,b->c,c->d,d->a",
      Answered: false,
      correct: false,
      selectedAns: [],
    },
    {
      QuestionNumber: "५",
      question: "5.सही विकल्प चुनें",
      type: "Multi Select",
      options: ["१>२", "५>=३", "१=0", "९<११"],
      Answer: "५>=३",
      Answered: false,
      correct: false,
      selectedAns: [],
    },
  ],
};
export default questionList;
